services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: meal-prep-db
    restart: always
    environment:
      POSTGRES_DB: meal_prep_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: meal-prep-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      # USDA API Configuration
      USDA_API_KEY: kNXQXGL92zW4fnMe5VxRHM6dHUvxaXwGsZ0MqUJ0
      USDA_API_URL: https://api.nal.usda.gov/fdc/v1
      
      # Database Configuration
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: meal_prep_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      
      # Flask Configuration
      FLASK_ENV: development
      FLASK_DEBUG: True
      PORT: 5000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: meal-prep-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      BACKEND_URL: http://backend:5000
      SECRET_KEY: change-this-in-production-to-random-string
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Volumes for data persistence
volumes:
  postgres_data:
    driver: local